version: '0.0.{build}'

image: Visual Studio 2017

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      CMAKE_GENERATOR: "Visual Studio 15 2017 Win64"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CMAKE_GENERATOR: "Visual Studio 14 2015 Win64"

platform:
  - x64

configuration:
  - Release
  - Debug

install:
    - git submodule update --init --recursive

before_build:
    - mkdir Build
    - cd Build
    - cmake -G "%CMAKE_GENERATOR%" ..

build:
  project: $(APPVEYOR_BUILD_FOLDER)\Build\$(APPVEYOR_PROJECT_NAME).sln

test_script:
  - ctest

