version: '0.0.{build}'

image: Visual Studio 2017

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      CMAKE_GENERATOR: Visual Studio 15 2017 Win64
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CMAKE_GENERATOR: Visual Studio 14 2015 Win64

platform:
    - x64

configuration:
    - Release
    - Debug

install:
    - git submodule update --init --recursive

    ############################################################################
    # Install a recent CMake
    ############################################################################
    - set CMAKE_URL="https://cmake.org/files/v3.10/cmake-3.10.0-rc5-win64-x64.zip"
    - appveyor DownloadFile %CMAKE_URL% -FileName cmake.zip
    - 7z x cmake.zip -oC:\projects\deps\cmake > nul
    - set PATH=C:\projects\deps\cmake\bin;%PATH%
    - cmake --version

before_build:
    - mkdir Build
    - cd Build
    - cmake -G "%CMAKE_GENERATOR%" ..

build:
    project: $(APPVEYOR_BUILD_FOLDER)\Build\$(APPVEYOR_PROJECT_NAME).sln

test_script:
    - ctest

