udo: required

language: cpp
jobs:
  include:
    - stage: test
      os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
         - MATRIX_EVAL="export CC=gcc-5 CXX=g++-5"
      script:
         - ./Scripts/travis-ci/test.bash

    - stage: test
      os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="export CC=gcc-6 CXX=g++-6"
      script:
         - ./Scripts/travis-ci/test.bash

    - stage: test
      os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="export CC=gcc-7 CXX=g++-7"
      script:
         - ./Scripts/travis-ci/test.bash
   
    - stage: test
      os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - MATRIX_EVAL="export CC=gcc-8 CXX=g++-8"
      script:
         - ./Scripts/travis-ci/test.bash
        
    - stage: test
      os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
         - MATRIX_EVAL="export CC=gcc-4.9 CXX=g++-4.9"
      script:
         - ./Scripts/travis-ci/test.bash

    - stage: test
      os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
        - MATRIX_EVAL="export CC=clang CXX=clang++"
      script:
         - ./Scripts/travis-ci/test.bash

    - stage: test
      os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
            - ubuntu-toolchain-r-test
          packages:
            - clang-4.0
            - g++-4.9
      env:
        - MATRIX_EVAL="export CC=clang-4.0 CXX=clang++-4.0"
      script:
         - ./Scripts/travis-ci/test.bash

    - stage: test
      os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
            - ubuntu-toolchain-r-test
          packages:
            - clang-5.0
            - g++-4.9
      env:
        - MATRIX_EVAL="export CC=clang-5.0 CXX=clang++-5.0"
      script:
         - ./Scripts/travis-ci/test.bash

    - stage: test
      os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-6.0
            - ubuntu-toolchain-r-test
          packages:
            - clang-6.0
            - g++-4.9
      env:
        - MATRIX_EVAL="export CC=clang-6.0 CXX=clang++-6.0"
      script:
         - ./Scripts/travis-ci/test.bash

    - stage: test
      os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-7
            - ubuntu-toolchain-r-test
          packages:
            - clang-7
            - g++-4.9
      env:
        - MATRIX_EVAL="export CC=clang-7 CXX=clang++-7"
      script:
         - ./Scripts/travis-ci/test.bash
    
    - stage: documentation
      script:
         - echo Deploying

branches:
    only:
      - master
      - devel
      - ci-experiments

