sudo: required

language: cpp
matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
         - MATRIX_EVAL="export CC=gcc-5 CXX=g++-5"

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="export CC=gcc-6 CXX=g++-6"

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="export CC=gcc-7 CXX=g++-7"
   
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - MATRIX_EVAL="export CC=gcc-8 CXX=g++-8"
        
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
         - MATRIX_EVAL="export CC=gcc-4.9 CXX=g++-4.9"

    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
        - MATRIX_EVAL="export CC=clang CXX=clang++"

    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
            - ubuntu-toolchain-r-test
          packages:
            - clang-4.0
            - g++-4.9
      env:
        - MATRIX_EVAL="export CC=clang-4.0 CXX=clang++-4.0"

    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
            - ubuntu-toolchain-r-test
          packages:
            - clang-5.0
            - g++-4.9
      env:
        - MATRIX_EVAL="export CC=clang-5.0 CXX=clang++-5.0"

    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-6.0
            - ubuntu-toolchain-r-test
          packages:
            - clang-6.0
            - g++-4.9
      env:
        - MATRIX_EVAL="export CC=clang-6.0 CXX=clang++-6.0"

    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-7
            - ubuntu-toolchain-r-test
          packages:
            - clang-7
            - g++-4.9
      env:
        - MATRIX_EVAL="export CC=clang-7 CXX=clang++-7"

branches:
    only:
      - master
      - devel
      - ci-experiments

script:
  - mkdir $HOME/usr
  - export PATH="$HOME/usr/bin:$PATH"
  - wget https://cmake.org/files/v3.9/cmake-3.9.1-Linux-x86_64.sh
  - chmod +x cmake-3.9.1-Linux-x86_64.sh
  - ./cmake-3.9.1-Linux-x86_64.sh --prefix=$HOME/usr --exclude-subdir --skip-license
  - cmake --version
  - eval "${MATRIX_EVAL}"
  - export CPLUS_INCLUDE_PATH=/usr/local/include
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER -DCMAKE_BUILD_TYPE=Release ..
  - make all
  - ctest .
